Logo added and headerprofile UI fix
ClubCloudTech/elemental-platform-bridge pull request #16
Opened 2022-08-29 10:52 UTC by SidHarsh25

2022-08-30 08:31 UTC, ccfredbaum commented on elemental/module/membership/library/class-loginhandler.php
> -		<a href="<?php echo esc_url($store_url); ?>" class="elemental-host-link">
please run wordpress check style going forward - but for today I will do it AFTER PR is merged on server.
esc_url( $store .... note the space between $ and (

2022-08-30 08:32 UTC, ccfredbaum commented on elemental/assets/css/elemental.css
> +.elementor-44807 .elementor-element.elementor-element-81c2990>.elementor-container {
Do not use elementor style sheets - rather create a class in the object and use it in our own CSS> Elementor sheets can change in document names etc and will not work across multiple servers as they are done by post name.

2022-08-30 08:43 UTC, ccfredbaum requested changes

2022-08-30 08:43 UTC, ccfredbaum commented on elemental/assets/css/elemental.css
> +.elementor-44807 .elementor-element.elementor-element-81c2990>.elementor-container {
(or you can apply the style elsewhere)

2022-08-30 08:43 UTC, ccfredbaum commented on elemental/module/membership/library/class-loginhandler.php
> +			<div class="elemental-primary-nav-img oneLogo" style="width:100%; height:49px; background-image: url(<?php echo esc_url($store_logo); ?> )"></div>
using camel case for style- should use dashes and all lower case.

2022-08-30 08:43 UTC, ccfredbaum commented on elemental/assets/css/elemental.css
>  .elemental-background-item {
I have fixed a few of these in main already - please rebase before sending through

2022-08-30 08:43 UTC, ccfredbaum commented on elemental/assets/css/elemental.css
> +    background: url(https://coadjute.app/wp-content/uploads/2022/08/Backgr_.jpg);
same as above re rebase

2022-08-30 08:43 UTC, ccfredbaum commented on elemental/module/membership/views/membership/view-edituser.php
> +    if (user_can($current_user, 'administrator')) {
This is not right - as only WordPress Admins can use this form - and tenant admin accounts have to use it - a better check is for a Tenant account user type, or currently "store_vendor" role

2022-08-30 08:43 UTC, ccfredbaum commented on elemental/module/membership/views/membership/view-edituser.php
> +                                    <label class="col-xs-3 control-label">Email address</label>
No translations - please use esc_html__( 'Email Address', 'elementalplugin' );  --- applies to all fields where text is output

2022-08-30 08:43 UTC, ccfredbaum commented on elemental/module/membership/views/membership/view-edituser.php
> +        echo 'Login as admin ';
same as above - tenant admins need to use this not just wordpress admins

2022-08-31 09:46 UTC, merged

2022-08-31 09:50 UTC, ccfredbaum requested changes
Please change your IDE to code style WordPress - you are checking in code in PEAR format and its undoing all of the standard formatting. I can fix by running phpcbf - but ideally code standard should be done before any merge - loginhandler is a particular issue

2022-08-31 09:58 UTC, SerhiiStarovoitov commented
> Please change your IDE to code style WordPress - you are checking in code in PEAR format and its undoing all of the standard formatting. I can fix by running phpcbf - but ideally code standard should be done before any merge - loginhandler is a particular issue

I will run it on the server for now.