sanbox ui fixes
ClubCloudTech/elemental-platform-bridge pull request #5
Opened 2022-08-10 10:11 UTC by SidHarsh25

2022-08-11 14:36 UTC, SerhiiStarovoitov commented
@ccfredbaum, this one contains CSS edits from Sid. Can be merged to main.

2022-08-12 13:47 UTC, SerhiiStarovoitov approved these changes

2022-08-16 09:10 UTC, ccfredbaum requested changes

2022-08-16 09:10 UTC, ccfredbaum commented on elemental/module/membership/library/class-loginhandler.php
> +	const SHORTCODE_COMPANY_EDIT = 'elemental_compant_edit';
Should this be company_edit

2022-08-16 09:10 UTC, ccfredbaum commented on elemental/module/membership/library/class-loginhandler.php
> +		// \add_action('wp_ajax_nopriv_send_contact',array(Factory::get_instance(LoginAjaxHandler::class), 'smtp_ajax_handler'), 10, 2);
Please remove commented out actions.

2022-08-16 09:10 UTC, ccfredbaum commented on elemental/module/membership/library/class-loginhandler.php
> +	//Registering Script
Doc Block comments. Please make them consistent to main including vars, outputs and params

2022-08-16 09:31 UTC, SidHarsh25 commented on elemental/module/membership/library/class-loginhandler.php
> +	//Registering Script
Documented all block comments.

2022-08-16 09:31 UTC, SidHarsh25 commented on elemental/module/membership/library/class-loginhandler.php
> +		// \add_action('wp_ajax_nopriv_send_contact',array(Factory::get_instance(LoginAjaxHandler::class), 'smtp_ajax_handler'), 10, 2);
removed unwanted and commented methods

2022-08-16 09:32 UTC, SidHarsh25 commented on elemental/module/membership/library/class-loginhandler.php
> +	const SHORTCODE_COMPANY_EDIT = 'elemental_compant_edit';
changed and to elemental_company_edit and pushed

2022-08-16 09:32 UTC, SidHarsh25 commented on elemental/module/membership/library/class-companyajax.php
> +        //     $alphabet = "abcdefghijklmnopqrs)-(@&!tuwxyzABCDEFGHIJKLM)-(@&!tNOPQRSTUWXYZ01234)-(@&!t56789";
removed this method

2022-08-16 10:27 UTC, merged